// Mobile Menu Toggle
document.addEventListener('DOMContentLoaded', function() {
    const mobileMenuBtn = document.querySelector('.mobile-menu-btn');
    const navMenu = document.querySelector('header nav ul');

    mobileMenuBtn.addEventListener('click', function() {
        navMenu.classList.toggle('active');
    });

    // Language Translation Data
    const translations = {
        en: {
            home: "Home",
            shop: "Shop",
            tailors: "Tailors",
            how_it_works: "How It Works",
            support: "Support",
            hero_title: "Custom Islamic Wear Delivered to Your Doorstep",
            hero_subtitle: "Halal-compliant, modest clothing tailored to your measurements",
            start_order: "Start Custom Order",
            find_tailor: "Find a Tailor Near You",
            featured_categories: "Our Featured Categories",
            panjabi: "Panjabi",
            jubba: "Jubba",
            burqa: "Burqa",
            salwar_kameez: "Salwar Kameez",
            shop_now: "Shop Now",
            how_it_works_title: "How Qaaf Corner Works",
            step1_title: "Choose Your Design",
            step1_desc: "Select from our collection or customize your own Islamic clothing design.",
            step2_title: "Provide Measurements",
            step2_desc: "Enter your measurements or schedule a video call with a tailor.",
            step3_title: "Select Fabric & Tailor",
            step3_desc: "Choose your preferred fabric and a skilled tailor near you.",
            step4_title: "Receive Your Order",
            step4_desc: "Get your custom-made Islamic clothing delivered to your doorstep.",
            testimonials_title: "What Our Customers Say",
            testimonial1_quote: "\"As an Imam, I appreciate the modest designs and halal approach. The Jubba fits perfectly!\"",
            testimonial2_quote: "\"Finally a platform that understands our needs for Islamic clothing. The quality is excellent.\"",
            testimonial3_quote: "\"The video measurement service was very helpful. My Panjabi fits better than store-bought ones.\"",
            cta_title: "Ready for Your Perfect Islamic Outfit?",
            cta_subtitle: "Join thousands of satisfied customers who trust Qaaf Corner for their modest fashion needs.",
            about_us: "About Qaaf Corner",
            about_desc: "Empowering the Muslim community with halal-compliant, custom-tailored Islamic clothing delivered to your doorstep.",
            quick_links: "Quick Links",
            contact_us: "Contact Us",
            address: "123 Islamic Street, Dhaka, Bangladesh",
            phone: "+880 1234 567890",
            copyright: "© 2023 Qaaf Corner. All Rights Reserved.",
            select_type: "Select Clothing Type",
            select_gender: "Select Gender & Age",
            men: "Men",
            women: "Women",
            children: "Children",
            select_category: "Select Category",
            abaya: "Abaya",
            thobe: "Thobe",
            next: "Next",
            customize_design: "Customize Your Design",
            upload_design: "Upload Your Design",
            fabric: "Fabric",
            cotton: "Cotton",
            linen: "Linen",
            mixed: "Mixed",
            silk: "Silk",
            color: "Color",
            custom_color: "Or enter HEX code:",
            collar_style: "Collar Style",
            standard: "Standard",
            mandarin: "Mandarin",
            band: "Band",
            embroidery: "Embroidery",
            none: "None",
            simple: "Simple",
            detailed: "Detailed",
            upload_embroidery: "Upload embroidery design:",
            previous: "Previous",
            provide_measurements: "Provide Your Measurements",
            measurement_method: "Measurement Method",
            enter_manually: "Enter Manually",
            video_call: "Video Call with Tailor",
            use_existing: "Use Existing Profile",
            required_measurements: "Required Measurements (in cm)",
            chest: "Chest:",
            waist: "Waist:",
            hips: "Hips:",
            length: "Length:",
            sleeve: "Sleeve Length:",
            shoulder: "Shoulder Width:",
            how_to_measure: "How to take measurements?",
            measurement_instructions: "Follow these instructions to get accurate measurements...",
            schedule_video_call: "Schedule Video Call with Tailor",
            date: "Date:",
            time: "Time:",
            contact_number: "Contact Number:",
            video_call_note: "Our tailor will call you at the scheduled time to take your measurements via video call.",
            review_order: "Review Your Order",
            order_details: "Order Details",
            delivery_options: "Delivery Options",
            home_delivery: "Home Delivery",
            store_pickup: "Store Pickup",
            full_name: "Full Name:",
            city: "City:",
            zip: "ZIP Code:",
            payment_summary: "Payment Summary",
            base_price: "Base Price:",
            tailor_fee: "Tailor Fee:",
            delivery_fee: "Delivery Fee:",
            service_fee: "Service Fee:",
            total: "Total:",
            payment_method: "Payment Method",
            cod: "Cash on Delivery",
            agree_terms: "I agree to the Terms & Conditions and Privacy Policy",
            place_order: "Place Order",
            order_success: "Order Placed Successfully!",
            order_confirmation: "Your order #QC12345 has been confirmed. We'll notify you when your item is ready.",
            estimated_delivery: "Estimated Delivery:",
            total_amount: "Total Amount:",
            back_to_home: "Back to Home",
            track_order: "Track Order",
            step1: "1. Select Type",
            step2: "2. Customize",
            step3: "3. Measurements",
            step4: "4. Checkout"
        },
        bn: {
            home: "হোম",
            shop: "শপ",
            tailors: "দর্জি",
            how_it_works: "এটি কিভাবে কাজ করে",
            support: "সাপোর্ট",
            hero_title: "আপনার দরজায় কাস্টম ইসলামিক পোশাক পৌঁছে দেওয়া",
            hero_subtitle: "হালাল-সম্মত, শালীন পোশাক আপনার পরিমাপ অনুযায়ী তৈরি",
            start_order: "কাস্টম অর্ডার শুরু করুন",
            find_tailor: "আপনার নিকটস্থ দর্জি খুঁজুন",
            featured_categories: "আমাদের বৈশিষ্ট্যযুক্ত বিভাগসমূহ",
            panjabi: "পাঞ্জাবী",
            jubba: "জুব্বা",
            burqa: "বুর্কা",
            salwar_kameez: "সালোয়ার কামিজ",
            shop_now: "এখনই কিনুন",
            how_it_works_title: "কাফ কর্নার কিভাবে কাজ করে",
            step1_title: "আপনার ডিজাইন নির্বাচন করুন",
            step1_desc: "আমাদের সংগ্রহ থেকে নির্বাচন করুন বা আপনার নিজের ইসলামিক পোশাক ডিজাইন কাস্টমাইজ করুন।",
            step2_title: "পরিমাপ প্রদান করুন",
            step2_desc: "আপনার পরিমাপ লিখুন বা একটি দর্জির সাথে ভিডিও কল নির্ধারণ করুন।",
            step3_title: "ফ্যাব্রিক এবং দর্জি নির্বাচন করুন",
            step3_desc: "আপনার পছন্দের ফ্যাব্রিক এবং আপনার নিকটস্থ একজন দক্ষ দর্জি নির্বাচন করুন।",
            step4_title: "আপনার অর্ডার গ্রহণ করুন",
            step4_desc: "আপনার কাস্টম-তৈরি ইসলামিক পোশাক আপনার দরজায় পৌঁছে দেওয়া হবে।",
            testimonials_title: "আমাদের গ্রাহকরা কি বলেন",
            testimonial1_quote: "\"একজন ইমাম হিসেবে, আমি শালীন ডিজাইন এবং হালাল পদ্ধতির প্রশংসা করি। জুব্বাটি পুরোপুরি ফিট হয়েছে!\"",
            testimonial2_quote: "\"অবশেষে একটি প্ল্যাটফর্ম যা ইসলামিক পোশাকের জন্য আমাদের চাহিদা বোঝে। গুণমান চমৎকার।\"",
            testimonial3_quote: "\"ভিডিও পরিমাপ পরিষেবা খুব সহায়ক ছিল। আমার পাঞ্জাবী দোকানে কেনা পাঞ্জাবীর চেয়ে ভাল ফিট হয়েছে।\"",
            cta_title: "আপনার নিখুঁত ইসলামিক পোশাকের জন্য প্রস্তুত?",
            cta_subtitle: "হাজারো সন্তুষ্ট গ্রাহকের সাথে যোগ দিন যারা তাদের শালীন ফ্যাশনের প্রয়োজনে কাফ কর্নারকে বিশ্বাস করে।",
            about_us: "কাফ কর্নার সম্পর্কে",
            about_desc: "মুসলিম সম্প্রদায়কে ক্ষমতায়ন করা হালাল-সম্মত, কাস্টম-তৈরি ইসলামিক পোশাক আপনার দরজায় পৌঁছে দেওয়ার মাধ্যমে।",
            quick_links: "দ্রুত লিঙ্ক",
            contact_us: "যোগাযোগ করুন",
            address: "১২৩ ইসলামিক স্ট্রিট, ঢাকা, বাংলাদেশ",
            phone: "+৮৮০ ১২৩৪ ৫৬৭৮৯০",
            copyright: "© ২০২৩ কাফ কর্নার। সর্বস্বত্ব সংরক্ষিত।",
            select_type: "পোশাকের ধরন নির্বাচন করুন",
            select_gender: "লিঙ্গ এবং বয়স নির্বাচন করুন",
            men: "পুরুষ",
            women: "মহিলা",
            children: "শিশু",
            select_category: "বিভাগ নির্বাচন করুন",
            abaya: "আবায়া",
            thobe: "থোব",
            next: "পরবর্তী",
            customize_design: "আপনার ডিজাইন কাস্টমাইজ করুন",
            upload_design: "আপনার ডিজাইন আপলোড করুন",
            fabric: "ফ্যাব্রিক",
            cotton: "কটন",
            linen: "লিনেন",
            mixed: "মিশ্র",
            silk: "সিল্ক",
            color: "রঙ",
            custom_color: "বা HEX কোড লিখুন:",
            collar_style: "কলার স্টাইল",
            standard: "স্ট্যান্ডার্ড",
            mandarin: "ম্যান্ডারিন",
            band: "ব্যান্ড",
            embroidery: "এমব্রয়ডারি",
            none: "কিছু না",
            simple: "সাধারণ",
            detailed: "বিস্তারিত",
            upload_embroidery: "এমব্রয়ডারি ডিজাইন আপলোড করুন:",
            previous: "পূর্ববর্তী",
            provide_measurements: "আপনার পরিমাপ প্রদান করুন",
            measurement_method: "পরিমাপ পদ্ধতি",
            enter_manually: "ম্যানুয়ালি লিখুন",
            video_call: "দর্জির সাথে ভিডিও কল",
            use_existing: "বিদ্যমান প্রোফাইল ব্যবহার করুন",
            required_measurements: "প্রয়োজনীয় পরিমাপ (সেমি তে)",
            chest: "বুক:",
            waist: "কোমর:",
            hips: "হিপ:",
            length: "দৈর্ঘ্য:",
            sleeve: "হাতার দৈর্ঘ্য:",
            shoulder: "কাঁধের প্রস্থ:",
            how_to_measure: "কিভাবে পরিমাপ নেবেন?",
            measurement_instructions: "সঠিক পরিমাপ পেতে এই নির্দেশাবলী অনুসরণ করুন...",
            schedule_video_call: "দর্জির সাথে ভিডিও কল নির্ধারণ করুন",
            date: "তারিখ:",
            time: "সময়:",
            contact_number: "যোগাযোগ নম্বর:",
            video_call_note: "আমাদের দর্জি নির্ধারিত সময়ে আপনাকে কল করে ভিডিও কলের মাধ্যমে আপনার পরিমাপ নেবে।",
            review_order: "আপনার অর্ডার পর্যালোচনা করুন",
            order_details: "অর্ডার বিবরণ",
            delivery_options: "ডেলিভারি অপশন",
            home_delivery: "বাড়িতে ডেলিভারি",
            store_pickup: "স্টোর থেকে গ্রহণ",
            full_name: "পুরো নাম:",
            city: "শহর:",
            zip: "জিপ কোড:",
            payment_summary: "পেমেন্ট সারাংশ",
            base_price: "বেস মূল্য:",
            tailor_fee: "দর্জি ফি:",
            delivery_fee: "ডেলিভারি ফি:",
            service_fee: "সেবা ফি:",
            total: "মোট:",
            payment_method: "পেমেন্ট পদ্ধতি",
            cod: "ক্যাশ অন ডেলিভারি",
            agree_terms: "আমি শর্তাবলী এবং গোপনীয়তা নীতি মেনে নিচ্ছি",
            place_order: "অর্ডার করুন",
            order_success: "অর্ডার সফলভাবে স্থাপন করা হয়েছে!",
            order_confirmation: "আপনার অর্ডার #QC12345 নিশ্চিত করা হয়েছে। আপনার আইটেম প্রস্তুত হলে আমরা আপনাকে জানাবো।",
            estimated_delivery: "আনুমানিক ডেলিভারি:",
            total_amount: "মোট পরিমাণ:",
            back_to_home: "হোমে ফিরে যান",
            track_order: "অর্ডার ট্র্যাক করুন",
            step1: "১. ধরন নির্বাচন",
            step2: "২. কাস্টমাইজ",
            step3: "৩. পরিমাপ",
            step4: "৪. চেকআউট"
        },
        ar: {
            home: "الصفحة الرئيسية",
            shop: "تسوق",
            tailors: "الخياطون",
            how_it_works: "كيف يعمل",
            support: "الدعم",
            hero_title: "ملابس إسلامية مخصصة يتم توصيلها إلى باب منزلك",
            hero_subtitle: "ملابس محتشمة وحلال مصممة حسب قياساتك",
            start_order: "ابدأ طلب مخصص",
            find_tailor: "ابحث عن خياط بالقرب منك",
            featured_categories: "فئاتنا المميزة",
            panjabi: "بنجابي",
            jubba: "جبة",
            burqa: "برقع",
            salwar_kameez: "سروال قميص",
            shop_now: "تسوق الآن",
            how_it_works_title: "كيف يعمل زاوية قاف",
            step1_title: "اختر تصميمك",
            step1_desc: "اختر من مجموعتنا أو قم بتخصيص تصميم ملابسك الإسلامية الخاصة.",
            step2_title: "تقديم القياسات",
            step2_desc: "أدخل قياساتك أو حدد موعد مكالمة فيديو مع خياط.",
            step3_title: "اختر القماش والخياط",
            step3_desc: "اختر القماش المفضل لديك وخياطًا ماهرًا بالقرب منك.",
            step4_title: "استلم طلبك",
            step4_desc: "احصل على ملابسك الإسلامية المخصصة التي يتم توصيلها إلى باب منزلك.",
            testimonials_title: "ما يقوله عملاؤنا",
            testimonial1_quote: "\"كإمام ، أقدر التصاميم المحتشمة والنهج الحلال. الجبة تناسب تمامًا!\"",
            testimonial2_quote: "\"أخيرًا منصة تفهم احتياجاتنا للملابس الإسلامية. الجودة ممتازة.\"",
            testimonial3_quote: "\"كانت خدمة القياس بالفيديو مفيدة للغاية. البنجابي الخاص بي يناسب أفضل من تلك المشتراة من المتجر.\"",
            cta_title: "هل أنت مستعد لملابسك الإسلامية المثالية؟",
            cta_subtitle: "انضم إلى الآلاف من العملاء الراضين الذين يثقون بزاوية قاف لاحتياجاتهم من الأزياء المحتشمة.",
            about_us: "حول زاوية قاف",
            about_desc: "تمكين المجتمع المسلم من خلال تقديم ملابس إسلامية مخصصة وحلال يتم توصيلها إلى باب منزلك.",
            quick_links: "روابط سريعة",
            contact_us: "اتصل بنا",
            address: "١٢٣ شارع إسلامي ، دكا ، بنغلاديش",
            phone: "+٨٨٠ ١٢٣٤ ٥٦٧٨٩٠",
            copyright: "© ٢٠٢٣ زاوية قاف. جميع الحقوق محفوظة.",
            select_type: "حدد نوع الملابس",
            select_gender: "حدد الجنس والعمر",
            men: "رجال",
            women: "نساء",
            children: "أطفال",
            select_category: "حدد الفئة",
            abaya: "عباية",
            thobe: "ثوب",